apiVersion: v1
kind: Service
metadata:
  name: dahl-{{ default "staging" .Release.Namespace }}-nginx
  labels:
    tier: backend
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: dahl-{{ default "staging" .Release.Namespace }}-nginx
    tier: backend
