apiVersion: apps/v1
kind: Deployment
metadata:
  name: dahl-{{ default "staging" .Release.Namespace }}-php
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dahl-{{ default "staging" .Release.Namespace }}-php
      tier: backend
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: dahl-{{ default "staging" .Release.Namespace }}-php
        tier: backend
        {{ if ne .Release.Namespace "production" }}name: dahl-{{ .Release.Namespace }}{{- else }}hostname: dahl{{- end }}
    spec:
      containers:
      - name: dahl-{{ default "staging" .Release.Namespace }}-php
        image: php:8-fpm
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
      volumes:
      - name: webroot
        nfs:
          path: /export/csweb/dahl
          server: cswebnfs-int.k8s.cs.calvin.edu
