apiVersion: apps/v1
kind: Deployment
metadata:
  name: dahl-{{ default "staging" .Release.Namespace }}-nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dahl-{{ default "staging" .Release.Namespace }}-nginx
      tier: backend
  template:
    metadata:
      labels:
        app: dahl-{{ default "staging" .Release.Namespace }}-nginx
        tier: backend
    spec:
      volumes:
      - name: webroot
        nfs:
          path: /export/csweb/dahl
          server: cswebnfs-int.k8s.cs.calvin.edu
      - name: config
        configMap:
          name: dahl-{{ default "staging" .Release.Namespace }}-nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: dahl-{{ default "staging" .Release.Namespace }}-nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
        - mountPath: /etc/nginx/conf.d
          name: config
